
renderingOptions:
  submitButtonLabel: Submit
identifier: FormConfigsplitExample
label: 'Example - Frontend configuration split'
type: Form
prototypeName: standard
finishers:
  -
    options:
      subject: 'Message sent by contact form'
      senderAddress: '{emailAddress}'
      senderName: '{name}'
      attachUploads: true
      recipients:
        your.company@example.com: 'Your Company name'
      addHtmlPart: true
    identifier: EmailToReceiver
  -
    options:
      message: 'Thank you for your message! We will get back to you as soon as possible.'
    identifier: Confirmation
renderables:
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    identifier: page-1
    label: ''
    type: Page
    renderables:
      -
        defaultValue: ''
        identifier: name
        label: Name
        type: Text
        properties:
          fluidAdditionalAttributes:
            required: required
        validators:
          -
            identifier: NotEmpty
      -
        defaultValue: ''
        identifier: emailAddress
        label: Email
        type: Text
        properties:
          fluidAdditionalAttributes:
            required: required
            placeholder: john@doe.com
        validators:
          -
            identifier: NotEmpty
          -
            identifier: EmailAddress
      -
        defaultValue: ''
        identifier: message
        label: Message
        type: Textarea
        properties:
          fluidAdditionalAttributes:
            placeholder: ''
            required: required
        validators:
          -
            identifier: NotEmpty
  -
    renderingOptions:
      previousButtonLabel: 'Previous step'
      nextButtonLabel: 'Next step'
    identifier: summarypage
    label: 'Summary page'
    type: SummaryPage
